### ISSUE TITLE
[1주차]  3장 고급 타입 - void 와 never 타입

### ISSUE THREAD

**Issue by qooktree1** [StudyForYou/ouahhan-typescript-with-react#1]
### Q. void 타입과 never 타입 둘 모두 `반환 값이 없음을 나타내는 타입`으로 알고 있는데 그럼 두 타입의 차이점은 무엇인가요??
주로 프로젝트에서 eventhandler 함수를 작성할 때 `void` 타입을 많이 사용했던 문법으로 기억합니다. 만약 반환 값이 없다는 것이 확실하다면 `never` 타입을 사용해도 되지 않는지 의문이 듭닌다.
```ts
handleSubmit: (val: number) => void;
```

**Comment by SoobinJ** [comment]
void: 값을 반환하지 않음을 의미
never: 값을 반환할 수 없음을 의미
맥락과 의미적인 차이가 존재한다고 합니다. void는 반환 값은 없지만, 함수가 정상적인 흐름으로 진행 후 종료됨을 나타냅니다. 하지만 never 타입은 함수가 반환하는 것이 아니라 계속 돌고 있다가 실행 흐름이 중단되며 값을 반환할 수 없음을 나타냅니다. 정리하면 never 타입은 특별한 상황에 사용된다고 생각하고, 대부분 함수에서는 다른 반환 타입을 선택하는게 좋을 것 같습니다. 반환 값이 없음이 확실하다고 해도 반환할 수 없음을 의미하는게 아니라 never 타입이 적합하지 않을 것 같습니다.!

**Comment by leegyuho-programer** [comment]
void: 함수가 아무것도 반환하지 않는 경우
never: 함수가 절대로 반환하지 않는 경우 / 함수가 끝나지 않거나 항상 예외가 발생하여 프로그램이 비정상적으로 종료되는 경우
void를 사용하는 것이 일반적이지만 해당 함수가 절대적으로 반환 값을 가질 수 없는 상황이라면 never 타입을 사용하는 것도 가능은 하다고 생각합니다.
