### ISSUE TITLE
#6 [3장_1] void 타입과 never 타입의 특징과 차이점을 알려주세요

### ISSUE THREAD

**Issue by qooktree1** [StudyForYou/ouahhan-typescript-with-react#18]
## ❓문제 
void 타입과 never 타입의 특징과 차이점을 알려주세요

## 🎯답변

**[특징]**

- void 타입은 아무런 값도 없음을 의미하는 타입입니다. 보통 아무런 값도 반환하지 않는 함수의 반환값 타입을 정의할 때 사용합니다.
- never 타입은 불가능을 의미하는 타입입니다. 보통 함수가 어떠한 값도 반환할 수 없는 상황(ex. 무한 루프, 에러 throw)에 사용합니다. 또한 조건부 타입에서 특정 조건을 만족하지 않는 경우의 결과에 never를 할당하여 엄격한 타입 검사 목적으로 사용하기도 합니다.

**[차이점]**

주로 함수에 사용하지만 변수에도 void와 never 타입을 설정할 수 있습니다. 이 때 각 타입에 할당할 수 있는 타입의 값에 차이가 있습니다.
- void 타입의 변수에는 undefined, null(strictNullChecks 옵션이 false일 때) 값을 담을 수 있습니다. 명시적인 의미를 부여하는 관점에서 굳이 void를 쓰지 않고 undefined, null 타입 키워드를 직접 사용하는 편이 좋습니다.
- never 타입의 변수에는 "any를 포함해" 그 어떠한 타입의 값도 담을 수 없습니다.

**Comment by drizzle96** [comment]
**[특징]**

- void 타입은 아무런 값도 없음을 의미하는 타입입니다. 보통 아무런 값도 반환하지 않는 함수의 반환값 타입을 정의할 때 사용합니다.
- never 타입은 불가능을 의미하는 타입입니다. 보통 함수가 어떠한 값도 반환할 수 없는 상황(ex. 무한 루프, 에러 throw)에 사용합니다. 또한 조건부 타입에서 특정 조건을 만족하지 않는 경우의 결과에 never를 할당하여 엄격한 타입 검사 목적으로 사용하기도 합니다.

**[차이점]**

주로 함수에 사용하지만 변수에도 void와 never 타입을 설정할 수 있습니다. 이 때 각 타입에 할당할 수 있는 타입의 값에 차이가 있습니다.
- void 타입의 변수에는 undefined, null(strictNullChecks 옵션이 false일 때) 값을 담을 수 있습니다. 명시적인 의미를 부여하는 관점에서 굳이 void를 쓰지 않고 undefined, null 타입 키워드를 직접 사용하는 편이 좋습니다.
- never 타입의 변수에는 "any를 포함해" 그 어떠한 타입의 값도 담을 수 없습니다.

**Comment by hyeyoonS** [comment]
### Void타입

- 값을 반환하지 않는 경우에 사용합니다.
    - 콘솔에 로그를 출력하는 함수
    - 다른 함수를 실행하는 역할만 하는 함수

```jsx
function shoModal(type:ModalType):void {
	feedbackSlice.actions.createModal(type);
	}
```

- void타입으로 지정된 변수는 undefined또는 null값만 할당 가능합니다.
    - 예외: strictNullChecks가 비활성화 된 경우

```jsx
let voidValue: void = undefined;
```

---

### Never타입

- 값을 반환할 수 없는 경우에 사용합니다.
    - 에러를 던지는 경우
    - 무한루프 함수

```jsx
function generateError(res:Response): never {
	throw new Error (res.getMessage();
}

function checkStatus(): never {
	while (true) {
	//...
	}
}
```

- never타입은 모든 타입의 하위 타입이며, 자신을 제외한 어떤 타입도 never에 할당할 수 없습니다.
- 엄격한 타입 검사의 목적을 위해 사용됩니다.
