### ISSUE TITLE
#7 [3장_1] 타입스크립트에서 배열을 다루는 이유에 대해서 설명해주세요!

### ISSUE THREAD

**Issue by hyeyoonS** [StudyForYou/ouahhan-typescript-with-react#19]
## ❓문제 
타입스크립트에서 배열을 다루는 이유에 대해서 설명해주세요!

## 🎯답변 요약
자바스크립트의 배열(Array 키워드)은 객체에 속하는 타입으로 분류되며 배열을 단독으로 배열이라는 자료형에 국한하지 않기 때문입니다.

## 🎯답변
일반적인 정적 언어에서는 배열의 원소들에 하나의 타입만 들어오도록 설계돼있습니다. 하지만 자바스크립트의 배열은 요소들이 어떤 타입인지 제한하지 않고 여러 타입을 혼합해 사용할 수 있습니다. 

```js
//이렇게 배열 안에 어느 타입이나 할당 가능
const array = [1, "string", fn];
```

이런 경우 타입 안정성이 떨어지기 때문에 타입스크립트에서는 배열 자료형을 따로 두어 배열의 요소가 지정한 타입을 따르도록 강제합니다.

**Comment by drizzle96** [comment]
자바스크립트의 배열(Array 키워드)은 객체에 속하는 타입으로 분류되며 배열을 단독으로 배열이라는 자료형에 국한하지 않기 때문입니다.
일반적인 정적 언어에서는 배열의 원소들에 하나의 타입만 들어오도록 설계돼있습니다. 하지만 자바스크립트의 배열은 요소들이 어떤 타입인지 제한하지 않고 여러 타입을 혼합해 사용할 수 있습니다. 이런 경우 타입 안정성이 떨어지기 때문에 타입스크립트에서는 배열 자료형을 따로 두어 배열의 요소가 지정한 타입을 따르도록 강제합니다.

**Comment by hyeyoonS** [comment]
- Array는 타입스크립트에서 배열의 타입을 확인하는 방법입니다.
- 자바스크립트에서 typeof로 타입을 확인할 수 있지만, 자바스크립트의 배열은 동적 언어의 특징에 따라 어떤 값이든 배열의 원소로 허용합니다.
    
    ```jsx
    const array = [1, "string", fn];
    ```
    
- 따라서 array타입을 선언함으로써 배열의 원소로 하나의 타입만 사용할 수 있도록 제한할 필요가  있습니다.
