### ISSUE TITLE
enum을 사용해야 할까?

### ISSUE THREAD

**Issue by qooktree1** [StudyForYou/ouahhan-typescript-with-react#2]
### enum을 사용해야 하는지 찾아보다가 좋은 블로그 있어 올려봅니다.
[TypeScript enum을 사용하지 않는 게 좋은 이유를 Tree-shaking 관점에서 소개합니다.](https://engineering.linecorp.com/ko/blog/typescript-enum-tree-shaking)

**Comment by drizzle96** [comment]
링크가 잘못 달린 것 같아요!

**Comment by qooktree1** [comment]
앗.. 그렇네요 다시 수정하겠습니다! 감사합니다!! :)
