### ISSUE TITLE
#14 [4장_3] 식별할 수 있는 유니온의 판별자로 사용할 수 있는 타입의 조건을 설명해주세요!

### ISSUE THREAD

**Issue by hyeyoonS** [StudyForYou/ouahhan-typescript-with-react#26]
## ❓문제 
식별할 수 있는 유니온의 판별자로 사용할 수 있는 타입의 조건을 설명해주세요!

## 🎯답변
- 프로퍼티가 리터럴 타입이어야 합니다.
- 판별자로 선정된 프로퍼티의 값에는 적어도 하나 이상의 유닛 타입이 포함되어야 하고, 인스턴스화할 수 없는 타입이어야 합니다.

**Comment by drizzle96** [comment]
- 프로퍼티가 리터럴 타입이어야 합니다.
- 판별자로 선정된 프로퍼티의 값에는 적어도 하나 이상의 유닛 타입이 포함되어야 하고, 인스턴스화할 수 없는 타입이어야 합니다.

**Comment by qooktree1** [comment]
1. 리터럴 타입이어야 합니다.
2. 인스턴스화할 수 있는 타입은 포함되지 않아야 한다.

**Comment by summerkimm** [comment]
1. 리터럴 타입이어야 한다.
2. 판별자로 선장한 값에 적어도 하나 이상의 유닛 타입이 포함되어야 하며, 인스턴스화 할 수 있는 타입은 포함되지 않아야 한다.

**Comment by hyeyoonS** [comment]
- 리터럴 타입이어야 한다.
- 판별자로 선정한 값에 적어도 하나 이상의 유닛 타입이 포함되어야 하며, 인스턴스화 할 수 있는 타입은 포함되지 않아야 한다.
