### ISSUE TITLE
타입 좁히기의 방식 (타입 가드 vs 타입 단언)

### ISSUE THREAD

**Issue by drizzle96** [StudyForYou/ouahhan-typescript-with-react#3]
타입을 좁히는 방법에는 책의 타입 가드 외에 타입 단언(as)도 있는데요.
둘의 비교와 개인적인 생각을 조금 적어봅니다!

- 타입 가드
   - 런타임에 값의 타입을 검사하여 타입 에러를 잡아낼 수 있어
   - 따라서 타입의 안정성을 보장할 수 있어
   - 코드가 길어지고 복잡한 상황에 조건을 완벽하게 세우기가 어려워
- 타입 단언
  - TS의 추론보다 개발자 입장에서 값의 타입에 대해 더 많이 알고 있을 때, 단언을 통해 타입을 재정의 할 수 있어
  - 추론이 제대로 되지 않는 경우에만 골라서 사용할 수 있기에 쉽게 사용 가능해
  - 반면 타입의 안정성을 보장할 수 없어(잘못된 단언을 하는 경우 런타입 에러가 발생할 수 있어)
- 결론
  - 타입을 확실히 아는 경우에는 타입 단언을 사용할 수는 있지만,
  - 일반적으로 타입 가드를 사용하는 편이 안정성 면에서 좋아
- 개인적인 생각
  웬만하면 타입스크립트가 추론을 잘하기 때문에 타입 좁히기를 자주 사용하지는 않는 것 같습니다. 그리고 추론이 마음대로 안되는 경우는 보통 상황이 복잡한 경우(혹은 라이브러리를 사용하는 경우)라서 빠른 개발을 위해 습관적으로 타입 단언을 평소에 거의 사용하고 있던 것 같습니다.
  현업에서는 나는 이 값이 이 타입인 것이 당연한데 추론이 안되는 경우에 상황이 복잡해서 타입 가드를 설정하면서 시간이 너무 오래 걸린다면, 차라리 빠르게 단언을 하고 넘어가는게 시간 효율 면에서 좋은 것 같기도 합니다. 
  하지만 좋은 개발자가 되기 위해서, 근본적으로 추론이 안되는 상황을 만든 원인(ex. 컴포넌트의 인터페이스를 잘 설계했는지, 라이브러리의 인터페이스가 어떻게 설계되어있는지)을 개선해서 타입 단언을 해야만 하는 상황이 되도록 안오도록 하는게 좋을 것 같습니다!

참고
https://velog.io/@dpldpl/%ED%83%80%EC%9E%85-%EA%B0%80%EB%93%9C%EC%99%80-%ED%83%80%EC%9E%85-%EB%8B%A8%EC%96%B8-TypescriptType-Assertion-vs-Type-Guard
https://pandaquests.medium.com/difference-between-type-guards-and-type-assertions-in-typescript-65e7d6625cd4

**Comment by qooktree1** [comment]
좋은 글 감사합니다 :)

저도 확실히 프로젝트 진행할 당시 시간 비용을 줄이기 위해 타입 단언을 자주 사용했던 것 같네요. (저는 `as` 와 `!` 두 개를 사용했었습니다)
