### ISSUE TITLE
#21 [8장_1] ReactElement, ReactNode, JSX.Element에 대해서 간단하게 설명해주세요!

### ISSUE THREAD

**Issue by hyeyoonS** [StudyForYou/ouahhan-typescript-with-react#33]
## ❓문제 
- ReactElement, ReactNode, JSX.Element에 대해서 간단하게 설명해주세요!

## **ReactElement**

```tsx
interface ReactElement<
  P = any,
  T extends string | JSXElementConstructor<any> =
    | string
    | JSXElementConstructor<any>
> {
  type: T;
  props: P;
  key: Key | null;
}
```

- React 컴포넌트의 구성 요소로, React에서 UI를 구축하는 기본 단위
- ‘type’, ‘props’, ’key’ 등의 속성을 가짐.
- ‘React.createElement’ 함수나 JSX를 통해 생성됨.
- 예시
    
    ```tsx
    const element = React.createElement('div', { className: 'container' }, 'Hello, World!');
    // 또는
    const element = <div className="container">Hello, World!</div>;
    ```
    

## **ReactNode**

```tsx
type ReactNode =
  | ReactElement
  | string
  | number
  | ReactFragment
  | ReactPortal
  | boolean
  | null
  | undefined;
```

- ReactElement 뿐만 아니라 string, number 등 다양한 타입 포함 가능함

## **JSX.Element**

```tsx
declare global {
  namespace JSX {
    interface Element extends React.ReactElement<any, any> { }
  }
}
```

- React.Element의 type, props 타입을 any로 두어 React.Element보다 타입을 느슨하게 검사하는 타입
- 함수형 컴포넌트의 리턴 타입으로, 다양한 커스텀 타입의 element를 구현하고 사용할 수 있음

**Comment by drizzle96** [comment]
React.ReactElement, JSX.Element, React.ReactNode는 모두 리액트 요소를 나타내는 타입입니다. 다만 각 타입은 아래처럼 약간의 차이를 보입니다.

1. React.ReactElement
- 함수 컴포넌트의 반환 타입으로 셋 중 기본 베이스입니다.
- 제네릭으로 props, type 타입을 받습니다.

2. JSX.Element
- React.ReactElement의 자식 타입으로 props,type 타입에 any가 들어갑니다.
- 글로벌 네임스페이스에 정의되어 있어 외부 라이브러리에서 컴포넌트 타입을 재정의 할 수 있는 유연성을 제공합니다.

3. React.ReactNode
- React.ReactElement 외에도 boolean, string, number 등의 여러 타입을 유니온으로 포함하는 넓은 타입입니다.

이런 차이로 인해 각 타입이 주로 활용되는 상황이 다음과 같습니다.

1. React.ReactNode
- React.ReactNode는 리액트의 render 함수가 반환할 수 있는 모든 형태를 담고 있습니다.
- 컴포지션 모델에서 children에는 여러 타입이 들어올 수 있습니다. 이렇게 넓은 형태를 주고 싶을 때 React.ReactNode를 사용할 수 있습니다.

2. JSX.Element
- JSX.Element는 props와 type 필드가 any 타입인 ReactElement 타입과 같습니다.
- 따라서 props를 모르는 컴포넌트를 render props 패턴에 사용할 때 활용할 수 있습니다. (사실 이런 경우에도 제네릭을 주지 않은 React.ReactElement를 사용하면 되긴 합니다)
- 외부 라이브러리가 자체 컴포넌트 시스템을 갖고 있거나 리액트와 다른 방식으로 JSX를 사용하는 경우에 사용할 수 있습니다.

3. React.ReactElement
- props, type을 더 좁게 추론하고 싶을 때 React.ReactElement의 제네릭으로 지정하는 식으로 활용할 수 있습니다. 
- props의 형태를 구체화했기 때문에 props에 접근할 때 목록이 추론되어 표시됩니다.

**Comment by hyeyoonS** [comment]
우선 JSX에 대해서 살펴볼 필요가 있습니다.
- JSX는 자바스크립트의 확장 문법으로, 리액트에서 UI를 표현하는 데 사용됩니다.
- JavaScript와 HTML을 조합한 문법을 사용하여 React 요소를 생성합니다.

⇒ 즉, JSX는 리액트 엘리먼트를 생성하기 위한 문법이며 트랜스파일러는 JSX 문법을 createElement 메서드 호출문으로 변환하여 리액트 엘리먼트를 생성합니다.

⇒ JSX 코드를 작성하면 해당 코드는 JSX.Element로 변환되고, 이는 React 애플리케이션에서 React.ReactElement로 변환됩니다. React.ReactNode은 React 애플리케이션에서 렌더링 가능한 모든 요소를 포함하는 범용적인 개념이며, JSX.Element는 TypeScript에서 JSX 요소의 타입을 정의하기 위해 사용됩니다.

---


![322454210-1feffd90-4f3e-427b-a1ee-883918d7d08b](https://github.com/StudyForYou/ouahhan-typescript-with-react/assets/144667455/fc0419d6-a51a-429d-85be-2059fdf4d977)
### React.ReactElement
- JSX를 통해 작성된 코드는 React.ReactElement로 변환됩니다.
- ReactElement 타입은 JSX의 createElement 메서드 호출로 생성된 리액트 엘리먼트를 나타내는 타입입니다.
⇒ 리액트 컴포넌트를 객체 형태로 저장하기 위한 포맷입니다.
- JSX.Element에서 props타입이 any일 경우 ⇒ ReactElement를 사용해서 제네릭에 직접 props타입을 명시할 수 있습니다.


```tsx
interface IconProps {
  size: number;
}

interface Props {
  // Item 컴포넌트의 props를 정의.
  // ReactElement의 props 타입으로 IconProps 타입 지정
  icon: React.ReactElement<IconProps>; // icon의 props의 타입은 IconProps
  // icon은 IconProps 타입의 props를 갖는 ReactElement임을 명시.
}

const Item = ({ icon }: Props) => {
  //icon을 props로 받음
  // icon prop으로 받은 컴포넌트의 props에 접근하면, props의 목록이 추론된다
  const iconSize = icon.props.size; // icon의 props에 접근.

  return <li>{icon}</li>;
};
```

### JSX.Element

⇒ 타입스크립트가 JSX를 사용할 때 정의하는 타입입니다.
- props와 타입 필드가 any 타입인 리액트 엘리먼트 타입과 같습니다. 
- 리액트 엘리먼트를 prop으로 전달받아 render props패턴으로 컴포넌트를 구현할 때 사용할 수 있습니다.

```tsx
// JSX.Element 타입을 사용하여 React 컴포넌트에서 자식 컴포넌트를 props로 전달하고,
// 그 자식 컴포넌트의 props에 접근하는 방법

//IconProps을 JSX.Element 타입으로 선언함으로써 해당 prop에는 JSX 문법만 삽입할 수 있다.
interface IconProps {
  icon: JSX.Element;
}

const Item = ({ icon }: IconProps) => {
  // icon을 prop으로 받음.
  // prop으로 받은 컴포넌트의 Iconprops에 접근할 수 있다
  const iconSize = icon.Iconprops.size; // icon의 props에 접근하여 size 속성을 가져옴.
  // icon이 JSX 요소이기 때문에 가능함.

  return <li>{icon}</li>;
};

// icon prop에는 JSX.Element 타입을 가진 요소만 할당할 수 있다
const App = () => {
  return <Item icon={<Icon size={14} />} />; // Icon컴포넌트는 JSX.Element 타입의 요소
};
```

### React.ReactNode 

- JSX를 사용하여 작성된 모든 구조 요소를 말합니다. 
⇒ React 컴포넌트의 렌더링 결과물로 나오는 **모든 종류의 Node를 나타내는 타입** 입니다.
⇒ 문자열, 숫자, 또는 ReactElement와 같은 JSX Element 등 다양한 종류의 값을 포함합니다.

- JSX형태의 문법을 어떤 타입이든 children prop으로 지정할 수 있게 하고 싶다면,  ReactNode 타입으로 children을 선언하면 된됩니다. 


```tsx
type ReactFragment = {} | Iterable<ReactNode>; // ReactNode의 배열 형태
type ReactNode =
  | ReactChild
  | ReactFragment
  | ReactPortal
  | boolean
  | null
  | undefined;
```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by summerkimm** [comment]
## **ReactElement**

```tsx
interface ReactElement<
  P = any,
  T extends string | JSXElementConstructor<any> =
    | string
    | JSXElementConstructor<any>
> {
  type: T;
  props: P;
  key: Key | null;
}
```

- React 컴포넌트의 구성 요소로, React에서 UI를 구축하는 기본 단위
- ‘type’, ‘props’, ’key’ 등의 속성을 가짐.
- ‘React.createElement’ 함수나 JSX를 통해 생성됨.
- 예시
    
    ```tsx
    const element = React.createElement('div', { className: 'container' }, 'Hello, World!');
    // 또는
    const element = <div className="container">Hello, World!</div>;
    ```
    

## **ReactNode**

```tsx
type ReactNode =
  | ReactElement
  | string
  | number
  | ReactFragment
  | ReactPortal
  | boolean
  | null
  | undefined;
```

- ReactElement 뿐만 아니라 string, number 등 다양한 타입 포함 가능함

## **JSX.Element**

```tsx
declare global {
  namespace JSX {
    interface Element extends React.ReactElement<any, any> { }
  }
}
```

- React.Element의 type, props 타입을 any로 두어 React.Element보다 타입을 느슨하게 검사하는 타입
- 함수형 컴포넌트의 리턴 타입으로, 다양한 커스텀 타입의 element를 구현하고 사용할 수 있음
