### ISSUE TITLE
[2주차] 타입 집합의 개념과 타입 호환성

### ISSUE THREAD

**Issue by hyeyoonS** [StudyForYou/ouahhan-typescript-with-react#5]
타입 집합, 타입 호환성에 대한 정리본입니당 ~.~ 
https://ts.winterlood.com/ 여기 참고했어요! 
초과프로퍼티검사에 대해서도 정리하고 싶었는데 그것은.... 다음주의 나에게...

# 타입 집합

### 타입은 여러 개의 값을 포함하는 `집합`이다.

> [!NOTE] 
> **집합**이란? 
> ⇒ 동일한 속성을 갖는 여러 개의 요소들을 하나의 그룹으로 묶은 단위

ex) number 타입은 -20, 3, 2, 4, 123, 0.12, ∞ 등의 값을 묶어 놓은 집합이다. 
그렇다면 오직 하나의 값만 포함하는 Number Literal 타입은?

```jsx
let num: 20 = 20;
```

20 이라는 Number Literal 타입이 존재한다면, 이 타입은 딱 하나의 값(20)만을 포함하는 아주 작은 집합이다.

그리고 20이라는 Number Literal 타입은, Number타입에 속하는 값이다.
 ⇒ 모든 Number Literal 타입은 Number의 `부분 집합`이다.

이 때 number 타입은 `슈퍼타입`(부모타입)이고, number literal 타입은 `서브타입`(자식타입)이다. 

![1](https://github.com/StudyForYou/ouahhan-typescript-with-react/assets/144667455/0a38661a-ffa4-45d8-9c8c-89a952cf07d3)

그리고 이러한 개념은 타입 계층도에 적용이 된다.

![2](https://github.com/StudyForYou/ouahhan-typescript-with-react/assets/144667455/9e76d85e-62a2-4e85-bf1a-92c8a22019e5)

![3](https://github.com/StudyForYou/ouahhan-typescript-with-react/assets/144667455/038944cf-b620-4179-8e6a-2e3697af970d)

# 타입 호환성

타입 호환성이란, 어떠한 타입을 다른 타입으로 취급해도 괜찮은지 판단하는 것을 말한다. 타입 호환성은 타입 계층도를 기준으로 판단할 수 있다. 

타입스크립트는 슈퍼타입의 값을 서브타입의 값으로 취급하는 것을 허용하지 않는다. 
반대로, 서브타입의 값은 슈퍼타입의 값으로 호환 가능하다.

![4](https://github.com/StudyForYou/ouahhan-typescript-with-react/assets/144667455/19bd58ae-e161-41ab-9e48-b3d23672fd99)

그리고 이 때 서브타입 ⇒ 슈퍼타입으로 호환하는 것을 `업캐스팅`이라고 한다. 반대로 슈퍼타입 ⇒ 서브타입으로 호환하는 것을 `다운캐스팅`이라고 한다. 

![5](https://github.com/StudyForYou/ouahhan-typescript-with-react/assets/144667455/06dee6da-f26a-4517-b1c4-f354b0f2b2bd)

```jsx
let num1: number = 10;
let num2: 10 = 10;

num1 = num2; // ✅ OK
num2 = num1; // ❌ NO
```

---

# 타입 계층도와 타입 호환성 예시

- `never`은 공집합으로, 모든 타입의 서브타입이다. 따라서 never타입은 모든 타입으로 업캐스팅이 가능하다.

```jsx
let neverVar: never;

let a: number = neverVar;            // never -> number
let b: string = neverVar;            // never -> string
let c: boolean = neverVar;           // never -> boolean
let d: null = neverVar;              // never -> null
let e: undefined = neverVar;         // never -> undefined
let f: [] = neverVar;                // never -> Array
let g: {} = neverVar;                // never -> Object

```

- 반대로, 어떤 타입도 never타입으로 다운캐스팅 할 수 없다.

```jsx
let a: never = 1;                 // number -> never ❌
let b: never = "hello";           // string -> never ❌
let c: never = true;              // boolean -> never ❌
let d: never = null;              // null -> never ❌
let e: never = undefined;         // undefined -> never ❌
let f: never = [];                // Array -> never ❌
let g: never = {};                // Object -> never ❌
```

- `unknown`은 모든 타입을 부분집합으로 갖는 타입스크립트 전체 집합이다. 모든 타입은 unknown으로 업캐스팅 할 수 있다.

**Comment by qooktree1** [comment]
그림으로 보니 이해가 잘 가네요! 타입 호환성에 대해 배우고 갑니다 👍👍


NIT.

타입 계층도와 타입 호환성 예시에서 할당 오류가 나타나 타입 오류가 나는지 확인이 어려운 것 같아요.
```ts
let neverVar: never;
let a: number = neverVar;  // 오류 발생 - Variable 'neverVar' is used before being assigned.
```

```ts
const neverFunc = (): never => {
    while(true){}
}

let num:number = neverFunc(); // 업캐스팅
let str:string = neverFunc();
let bool:boolean = neverFunc()
```
- 함수 안의 결과값을 무한루프로 동작하게 되면 never 타입을 사용 가능한 것으로 아는데 이런 예제는 어떤가요???

**Comment by leegyuho-programer** [comment]
```ts
let neverVar: never;
let a: number = neverVar;  // 오류 발생 - Variable 'neverVar' is used before being assigned.
```
이 코드에 대해 종민님이 말씀하신 부분은 never 타입은 모든 타입의 서브타입이므로, 다른 타입으로 변환될 수 있어서 의미상으로는 맞지만 never 타입이 가질 수 있는 유일한 값은 undefined이며, 그 외의 값은 가질 수 없기 때문에 실제로는 사용할 수 없어서 오류로 나타나는 것 같습니다.
