### ISSUE TITLE
식별할 수 있는 유니온

### ISSUE THREAD

**Issue by SoobinJ** [StudyForYou/ouahhan-typescript-with-react#7]
### 1. 에러 정의하기 (P.139~141)

- 책의 예시에서 errorArr가 예상과 달리 타입 에러가 발생하지 않는다고 했습니다.
  ```ts
  type TextError = {
    errorCode: string;
    errorMessage: string;
  };

  type ToastError = {
    errorCode: string;
    errorMessage: string;
    toastShowDuration: number;
  };

  type AlertError = {
    errorCode: string;
    errorMessage: string;
    onConfirm: () => void;
  };

  type ErrorFeedbackType = TextError | ToastError | AlertError;

  const errorArr: ErrorFeedbackType[] = [
    //...
    {
      errorCode: "999",
      errorMessage: "msg",
      toastShowDuration: 3000,
      onConfirm: () => {},
    },
  ];
  ```
- 이때 책에서는 이유를 '자바스크립트는 덕 타이핑 언어이기 때문에'라고 하였는데 
- 정확히 왜 덕 타이핑언어이기 때문에 에러를 뱉지 않는지 궁금합니다.
- 제가 대략적으로 이해한 내용
=> 덕 타이핑은 정의된 타입이 아니더라도 정의된 타입과 같은 shape을 가지고 있으면 타입체크에서 에러가 나오지 않는다.
=> 그럼 shape이 같다는 것이 어떤 말인지..?
=> 우선, 같아서 에러가 발생하지 않았다..
=> 이후, '2. 식별할 수 있는 유니온'에서 구조 호환을 막기 위한 errorType을 추가함으로써 이전에는 식별되지 않은 타입을 식별하게 하고
=> 식별이 되기 때문에 우리가 위와 같은 코드에서 타입 에러가 발생할 수 있게 된다. 
=> 이런식으로 대략 이해하였는데 조금 더 정확하고 명확하게 설명해주실 수 있을까요??? (덕 타이핑 - > 타입 에러)

**Comment by qooktree1** [comment]
음... 일단 제가 이해한 것을 적어보도록 하겠습니다. 잘못된 점이 있다면 즉시 말씀해주세요!!!!
제가 설명을 못하는 부분 양해부탁드리겠습니다... 😭😭

1. shape 는 구조라고 생각하면 될 것 같습니다.
2. 구조적 타이핑에 대해 쉽게 이해한 바를 예를 들어보겠습니다.

집합의 개념으로
```ts
{
  errorCode: "999",
  errorMessage: "msg",
  toastShowDuration: 3000,
  onConfirm: () => {},
}
// 위의 객체를 A라 칭하겠습니다.
// TextError를 B, ToastError를 C, AlertError를 D라 칭하겠습니다.
// B는 A의 부분집합, C는 A의 부분집합, D는 A의 부분집합
// 정의된 타입 - B, C, D / 정의된 타입과 같은 구조 - A
```
- 구조적 타이핑에 관해서 사진과 글이 잘 작성되어 있다고 생각하여 첨부합니다.
[덕 타이핑과 구조적 타이핑](https://vallista.kr/%EB%8D%95-%ED%83%80%EC%9D%B4%ED%95%91%EA%B3%BC-%EA%B5%AC%EC%A1%B0%EC%A0%81-%ED%83%80%EC%9D%B4%ED%95%91/)
